# Generated by Django 5.2.8 on 2026-02-17 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='chatrequest',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_chat_request'),
        ),
        migrations.AddConstraint(
            model_name='chatrequest',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='prevent_self_request'),
        ),
    ]
